# package_size
#
# Tells the reporter how many headlines to produce by run
# It is also used as the number of latest headlines to be shown
# Default: 5
package_size: 5

# update_interval
#
# The number of minutes to wait before sending the reporters out to update the
# local news base. The reporters can potentially use external resources like
# network and disk, so please exercise wisdom when setting the interval.
#
# Set to 0 to send them out everytime a request arrives and to not record
# anything locally (useful for testing and debugging)
update_interval: 10

# Subversion specific settings
subversion:

# subversion/repo
#
# Tells the reporter where to find your project's repository
# Default: https://svn.sourceforge.net/svnroot/motiro
  repo: https://svn.sourceforge.net/svnroot/motiro
  
# Darcs specific settings
# Uncomment the lines below to activate darcs reporting
# darcs:

# darcs/repo
# Tells the reporter where to find the project's central repository
#   repo: http://motiro.sf.net/darcsrepos/trunk
